# Generated by Django 3.1 on 2020-08-25 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, 'fragile'), (2, 'robust'), (3, 'perishable')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StorageUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.CharField(max_length=100)),
                ('type_of_goods', models.CharField(max_length=50)),
                ('start_date_of_storage', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
