# Generated by Django 3.1 on 2020-09-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_delivery_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.slot'),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='date_of_pickup',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='time_of_pickup',
            field=models.CharField(max_length=50),
        ),
    ]
