# Generated by Django 3.1 on 2020-08-27 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200826_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_of_good', models.ImageField(upload_to='slots/')),
                ('name_of_good', models.CharField(max_length=250)),
                ('mass_of_good', models.IntegerField(max_length=50)),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='store.userprofile')),
            ],
        ),
    ]
