# Generated by Django 3.1 on 2020-09-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
