# Generated by Django 3.1 on 2020-09-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200901_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
