# Generated by Django 3.1 on 2020-08-28 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200828_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_good', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_pickup', models.DateField()),
                ('time_of_pickup', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
