# Generated by Django 3.1 on 2020-08-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200827_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='categories/')),
                ('cost', models.IntegerField()),
                ('slots_remaining', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='mass_of_good',
            new_name='mass_of_good_in_kgs',
        ),
    ]
