# Generated by Django 3.1 on 2020-08-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200827_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='mass_of_good',
            new_name='mass_of_good_in_kgs',
        ),
    ]
