# Generated by Django 3.1 on 2020-08-27 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_auto_20200827_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goods_slots',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='porsche.jpg', upload_to='media/'),
        ),
    ]
