# Generated by Django 3.1 on 2020-08-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200827_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location_address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
