# Generated by Django 3.1 on 2020-08-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200827_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goods_slots',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.goods'),
        ),
    ]
