# Generated by Django 3.1 on 2020-08-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_userprofile_location_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('charges', models.IntegerField()),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
