# Generated by Django 3.1 on 2020-08-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='contact',
            field=models.CharField(max_length=300),
        ),
    ]
