# Generated by Django 3.1 on 2020-08-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200828_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageunits',
            name='slots',
            field=models.IntegerField(),
        ),
    ]
